// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0wo-3kokmFPa-A3wtSfmdPUr5FIrqQ3A',
    appId: '1:792037978617:web:42504c6c1aee1b5450cd28',
    messagingSenderId: '792037978617',
    projectId: 'testsendotp-50c2f',
    authDomain: 'testsendotp-50c2f.firebaseapp.com',
    storageBucket: 'testsendotp-50c2f.appspot.com',
    measurementId: 'G-5J3CC18D6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaesaE5BevnsIOk83i02LFP5OtSMJPulw',
    appId: '1:792037978617:android:667d3357c598f48e50cd28',
    messagingSenderId: '792037978617',
    projectId: 'testsendotp-50c2f',
    storageBucket: 'testsendotp-50c2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6tBw6GWKTsOATYr_9NV2Wx07f6xz_ctk',
    appId: '1:792037978617:ios:730317b64ec5881050cd28',
    messagingSenderId: '792037978617',
    projectId: 'testsendotp-50c2f',
    storageBucket: 'testsendotp-50c2f.appspot.com',
    iosClientId: '792037978617-300q8pbrs9mspla1jtvev211il350hi1.apps.googleusercontent.com',
    iosBundleId: 'com.example.sendOtpFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6tBw6GWKTsOATYr_9NV2Wx07f6xz_ctk',
    appId: '1:792037978617:ios:730317b64ec5881050cd28',
    messagingSenderId: '792037978617',
    projectId: 'testsendotp-50c2f',
    storageBucket: 'testsendotp-50c2f.appspot.com',
    iosClientId: '792037978617-300q8pbrs9mspla1jtvev211il350hi1.apps.googleusercontent.com',
    iosBundleId: 'com.example.sendOtpFirebase',
  );
}
